### PR TITLE
updatedpattern12

### PR DESCRIPTION
**Pull request by 6736-shafi**
bro i hava add pattern12 as  Sandglass Star Pattern
please marge it

### CODE REVIEW

**Comment by 6736-shafi** [comment]
hi bro please let me know if you feel any changes

**Comment by 6736-shafi** [comment]
bro my final commit is amazing i have add two probles 
please do look my last commit or pr you will love it

**Comment by Yashkapure06** [comment]
> bro my final commit is amazing i have add two probles please do look my last commit or pr you will love it

Hey, 
Thank you for contributing.
I will look into it. Give me some time :)

**Comment by 6736-shafi** [comment]
Is this project listed  on hacktoberfest?

**Comment by 6736-shafi** [comment]
thanks you so much sir
sir can i start contributing to this repo ?

**Comment by 6736-shafi** [comment]
sir i have fixed #2 issued please have a look

**Pull request merged**
